# Server Port
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/talentbridge
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Secret key (at least 256 bits / 32 characters for HS256)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Token validity: 24 hours in milliseconds (86,400,000 ms)
jwt.expiration=86400000